src/main/java/edu/chl/group9/tomaxus/model/Category.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.group9.tomaxus.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 *
 * @author Daniel
 */
@Entity
public class Category implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private String description;
    @OneToMany
    private List<Event> events;
    private String imageURL;
    public static final String DEFAULT_CATEGORY_IMAGE = "../images/profile/Sample_Profile_Image.png";

    public Category() {
    }

    public Category(String name, String description, List<Event> events) {
        this.name = name;
        this.description = description;
        if(events != null) {
            this.events = events;
        } else {
            this.events = new ArrayList<>();
        }
    }

    public Category(String name, String desc) {
        this.name = name;
        description = desc;
        this.events = new ArrayList<>();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void addEvent(Event ev) {
        events.add(ev);
    }

    public void removeEvent(Event ev) {
        events.remove(ev);
    }

    public void removeAll() {
        events.clear();
    }

    public List<Event> getEvents() {
        return events;
    }

    public boolean containsEvent(Event ev) {
        if (events.contains(ev)) {
            return true;
        } else {
            return false;
        }
    }

    public String getImageURL() {
        if (imageURL != null) {
            return imageURL;
        } else {
            return DEFAULT_CATEGORY_IMAGE;
        }
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Category) {
            Category other = (Category) obj;
            return hashCode() == other.hashCode();
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + Objects.hashCode(this.id);
        hash = 61 * hash + Objects.hashCode(this.name);
        hash = 61 * hash + Objects.hashCode(this.description);
        return hash;
    }
    
    public int getNumberOfEvents() {
        return events.size();
    }
}

src/main/java/edu/chl/group9/tomaxus/model/Event.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.group9.tomaxus.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Class representing an event.
 * 
 * Default sorting is by title ascending.
 *
 * @author Erik
 */
@Entity
public class Event implements Serializable, Comparable<Event> {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;
    @Column(length=1000)
    private String eventDescription;
    @Column(length=100)
    private String eventTitle;
    private boolean isPrivate;
    private boolean isAccomplished;
    
    public static final String DEFAULT_EVENT_IMAGE = "../images/profile/Sample_Profile_Image.png";
    
    @Embedded
    private Location loc;
    @OneToOne
    private TUser owner;
    @OneToMany
    private List<TUser> participants;
    @OneToOne(cascade= CascadeType.ALL)
    private EventTimeRange timerange = new EventTimeRange();
    @Temporal(TemporalType.DATE)
    private Date timeCreated;
    private long imageId;
    


    
    public Event() {
        participants = new ArrayList<>();
        timeCreated = Calendar.getInstance().getTime();
    }
    
    public Event(String title, String description, Location loc, TUser owner, boolean isPrivate){
        this.eventTitle = title;
        this.eventDescription = description;
        this.loc = loc;
        this.owner = owner;
        this.isPrivate = isPrivate;    
        this.participants = new ArrayList<>();
        participants.add(owner);
        timeCreated = Calendar.getInstance().getTime();
    }
    
    public long getId() {
        return id;
    }
    
    public String getDescription() {
        return eventDescription;
    }
    
    public void setDescription(String description) {
        this.eventDescription = description;
    }
    
    public void setTitle(String title) {
        this.eventTitle = title;
    }
    
    public String getTitle() {
        return eventTitle;
    }
    
    public TUser getOwner() {
        return owner;
    }
    
    public void setOwner(TUser owner) {
        this.owner = owner;
    }

    public List<TUser> getParticipants() {
        return participants;
    }
    
    public int getNumberOfParticipants() {
        return participants.size();
    }
    
    public void addParticipant(TUser u) {
        participants.add(u);
    }
    
    public void removeParticipant(TUser u) {
        participants.remove(u);
    }
    
    public void setLocation(Location loc) {
        this.loc = loc;
    }
    
    public Location getLocation() {
        return loc;
    }
    
    public void setIsPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }
    
    public boolean getIsPrivate() {
        return isPrivate;
    }

    public boolean isIsAccomplished() {
        return isAccomplished;
    }

    public void setIsAccomplished(boolean isAccomplished) {
        this.isAccomplished = isAccomplished;
    }
    
    public void setEventTimeRange(EventTimeRange range) {
        this.timerange = range;
    }
    
     public EventTimeRange getEventTimeRange() {
        return timerange;
    }
    /*
    public void setCategory(Category cat) {
        this.cat.add(cat);
    }
    
    public List<Category> getCategory() {
        return cat;
    }
    */
    public void setTimeCreated(Date time) {
        this.timeCreated = time;
    }
    
    public Date getTimeCreated() {
        return timeCreated;
    }

    public long getImageId() {
        return imageId;
    }

    public void setImageId(long imageId) {
        this.imageId = imageId;
    }


    @Override
    public boolean equals(Object obj) {
        if(obj == null ) {
            return false;
        }
        if( obj.getClass().equals(this.getClass()) ) {
            try {
                Event other = (Event) obj;
                return other.hashCode() == this.hashCode();
            } catch(Exception e) {
                return false;
            }
        }
        return false;
    }

    @Override
    public int hashCode() {
        return eventTitle.hashCode() + eventDescription.hashCode();
    }

    /**
     * Default sorting is by title ascending.
     * 
     * TODO: Extend it to several sorting methods.
     * 
     * @param o
     * @return 
     */
    @Override
    public int compareTo(Event o) {
        return eventTitle.compareTo(o.getTitle());
    }

    @Override
    public String toString() {
        return "Event { id=" + id + ", title=" + eventTitle +", desc=" + eventDescription + " } ";
    }

}

src/main/java/edu/chl/group9/tomaxus/model/TUser.java
 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.group9.tomaxus.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;

/**
 *
 * A class representing a user.
 * 
 * 
 * @author group9
 */
@Entity
public class TUser implements Serializable, Comparable<TUser> {
    
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    private String username;
    private String fname;
    private String lname;
    private int age;
    private String gender;
    private String password;
    
    @Embedded
    private Location loc = new Location();
    @OneToMany
    private List<TUser> friends;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date timeJoined;

    private long profileImageId;
    
    public TUser() {
    }
    
    
    public TUser(String username, String fname, String lname) {
        this.username = username;
        this.fname = fname;
        this.lname = lname;
        friends = new ArrayList<>();
    }
    
    public TUser(String username, String fname, String lname, String gender, int age, Location l) {
        this.username = username;
        this.fname = fname;
        this.lname = lname;
        this.gender = gender;
        this.age = age;
        this.loc = l;
        friends = new ArrayList<>();
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getPassword() {
       return password;
    }

    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public void setAge(int age){
        this.age = age;
    }
    
    public int getAge(){
        return age;
    }
    
    public String getGender(){
        return gender;
    }
    
    public void setGender(String gender){
        this.gender = gender;
    }
    
    public Location getLoc() {
        return loc;
    }

    public void setLoc(Location loc) {
        this.loc = loc;
    }
    
    public long getProfileImageId() {
        return profileImageId;
    }

    public void setProfileImageId(long profileImageId) {
        this.profileImageId = profileImageId;
    }
    
     /**
     * Removes a friend from the friends-list.
     * 
     * Do a update on the TUser-object afterwards.
     * 
     * @param id TUser id to remove
     * @return true if it was true.
     * otherwise false
     */
    public boolean removeFriend(TUser other) {
        friends.remove(other);
        return true;
    }
    public List<TUser> getFriends() {
        return friends;
    }
    
    public boolean isFriendsWith(TUser other) {
        return friends.contains(other);
    }
        
    public boolean getHasCustomImage() {
        return profileImageId != 0;
    }
    
    public void clearFriends(){
        friends.clear();
    }
    
    public void addFriend(TUser user) {
        friends.add(user);
    }
    
    public Date getTimeJoined() {
        return timeJoined;
    }
    
    public void setTimeJoined(Date time) {
        this.timeJoined = time;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof TUser) {
            TUser other = (TUser) obj;
             return hashCode() == other.hashCode();
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        hash = 97 * hash + Objects.hashCode(this.username);
        hash = 97 * hash + Objects.hashCode(this.fname);
        hash = 97 * hash + Objects.hashCode(this.lname);
        return hash;
    }

    @Override
    public int compareTo(TUser o) {
        return (fname+lname).compareTo(o.fname+o.lname);
    }

    @Override
    public String toString() {
        return username;
    }
    
    
    
    
}

src/main/webapp/restricted/create_message.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="template.xhtml">

            <ui:define name="top">
               
            </ui:define>

            <ui:define name="left">
                
            </ui:define>
            
            <ui:define name="content">
            <h:outputStylesheet library="css" name="Messaging.css"  />
                  <h1>
                        New message
                   </h1>
                <h:form >
                    <table>
                        <tr>
                            <td class="inputDeclarations"><h:outputLabel for="messageTo" value="Message To:" /></td>
                            <td><h:inputText id="messageTo" value="#{createmessage.messageTo}" class="inputText"  binding="#{createmessage.messageToTextField}"/> </td>
                            <td><h:message for="messageTo"></h:message> </td>
                        </tr>
                        <tr>
                            <td class="inputDeclarations"><h:outputLabel for="title" value="Title" /></td>
                            <td><h:inputText id="title" value="#{createmessage.title}" class="inputText"  > Message content. </h:inputText></td>
                        </tr>
                        <tr>
                            <td class="inputDeclarations"><h:outputLabel for="content" value="Content" /></td>
                             <td><h:inputTextarea id="content" value="#{createmessage.content}"  class="inputTextArea" /> </td>
                      
                        </tr>
                        <tr>
                            <td>
                                
                            </td>
                            <td>
                                  <h:commandButton id="btnOK" value="Send Message" action="#{createmessage.sendMessage()}" />
                            </td>
                        </tr>
                    </table>
                  
                </h:form>
            </ui:define>
            
            

            <ui:define name="bottom">
               
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/restricted/findevent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <body>

        <ui:composition template="template.xhtml">

            <ui:define name="top">
               
            </ui:define>

            <ui:define name="left">
                Page one left                
            </ui:define>
            
            <ui:define name="content">
                <h:outputStylesheet library="css" name="Profile.css"  />
                <h1>
                    #{findEvents.categoryTitle}
                </h1>
                <c:forEach items="#{findEvents.events}" var="profileEvent">      
                    <h:form>
                        <h:commandLink  actionListener="#{showEvent.setEvent(profileEvent.id)}"  action="event.xhtml?faces-redirect=true" >
                            <div class="userEvent">

                                <div class="eventDetails">
                                    <div class="eventHeader">
                                            #{profileEvent.title}
                                    </div>
                                    <div class="eventDesc" >
                                           #{profileEvent.description}
                                    </div>
                                    <div class="eventImage">
                                        <h:graphicImage url="../images/profile/sample_Event_image.png" class="friends_image" />
                                    </div>
                                    <div class="eventStatistics" >
                                        <br/>
                                            #{profileEvent.numberOfParticipants} people has joined this event. Created: #{profileEvent.timeCreated}
                                    </div>
                                </div>
                            </div>
                        </h:commandLink>
                    </h:form>
                </c:forEach>
                
            </ui:define>
            
            

            <ui:define name="bottom">
               
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/restricted/friends.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
    </h:head>

    <body>
        <ui:composition template="./template.xhtml" >
            <ui:define name="content">
                <h:outputStylesheet library="css" name="Friends.css"  />
                <div>
                    <div class="topActionMenu">
                        <div class="topNameHeader">
                            Your friends
                        </div>
                    </div>

                    <div class="middleSection"> 
                        <div class="friendslist">

                            <c:forEach items="#{friends.list}" var="myFriend">
                                <h:form>
                                    <h:commandLink  actionListener="#{profile.setUser(myFriend.id)}"  action="profile.xhtml?faces-redirect=true" >
                                        <div class="friend_item">
                                            <c:if test="${myFriend.hasCustomImage}">
                                                <h:graphicImage value="image?id=#{myFriend.profileImageId}" class="friends_image" />
                                            </c:if>
                                            <c:if test="${!myFriend.hasCustomImage}">
                                                <c:if test="${myFriend.gender == 'Male'}">
                                                    <h:graphicImage url="../images/profile/abstract_boy.jpg" class="friends_image" />
                                                </c:if>
                                                <c:if test="${myFriend.gender == 'Female'}">
                                                    <h:graphicImage url="../images/profile/abstract_girl.jpg" class="friends_image" />
                                                </c:if>
                                            </c:if>
                                            <div class="friend_info">
                                                #{myFriend.fname} #{myFriend.lname}
                                            </div>
                                            <div class="friend_location">
                                                #{myFriend.loc}
                                            </div>
                                        </div>
                                    </h:commandLink>
                                </h:form>
                            </c:forEach>

                        </div>
                    </div>
                    <div class="bottomSection">


                        <h2>
                            <br />
                            Activity in your network
                        </h2>

                        <c:forEach items="#{friends.flow}" var="f">      
                            <h:form>
                                <h:commandLink  actionListener="#{showEvent.setEvent(f.eid)}"  action="event.xhtml?faces-redirect=true" >
                                    <div class="flowEvent">

                                        <div class="flowEventDetails">
                                            <div class="eventHeader">
                                                #{f.text}
                                            </div>
                                            <div class="flowEventDesc" >
                                                
                                            </div>
                                          
                                        </div>
                                    </div>
                                </h:commandLink>
                            </h:form>
                        </c:forEach>
                    </div>    
                </div>                    

            </ui:define>
        </ui:composition>

    </body>
</html>

src/main/webapp/restricted/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
    </h:head>

    <body>
        <ui:composition template="./template.xhtml" >
            <ui:define name="content">
                <h:outputStylesheet library="css" name="Profile.css"  />
                <div>
                    <div class="topActionMenu">
                        <div class="topNameHeader">
                            #{profile.fname} #{profile.lname}
                        </div>
                        <div class="actionlinks">                          

                            <c:choose>
                                <c:when test="${profile.isThisMe}">
                                    This is you.
                                </c:when>

                                <c:when test="${profile.isFriendsWith}">
                                    <h:form>
                                        <h:commandLink  actionListener="#{profile.removeAsFriend()}"  action="profile.xhtml?faces-redirect=true" > 
                                            Remove from friends
                                        </h:commandLink>
                                    </h:form>
                                    <h:form>
                                       <h:commandLink action="create_message.xhtml" actionListener="#{createmessage.setMessageTo(profile.getUsername())}" >
                                           Send Message
                                       </h:commandLink>
                                   </h:form>
                                </c:when>

                                <c:when test="${!profile.isFriendsWith}">
                                    <h:form>
                                        <h:commandLink  actionListener="#{profile.addAsFriend()}"  action="profile.xhtml?faces-redirect=true" > 
                                            Add as friend
                                        </h:commandLink>
                                    </h:form>
                                    <h:form>
                                       <h:commandLink action="create_message.xhtml" actionListener="#{createmessage.setMessageTo(profile.getUsername())}" >
                                           Send Message
                                       </h:commandLink>
                                   </h:form>
                                </c:when>
                            </c:choose>
                        </div>
                      </div>
                    <div class="middleSection"> 
                        <c:if test="${profile.hasCustomImage}">
                            <h:graphicImage value="image?id=#{profile.imageId}" class="profile_image" />
                        </c:if>
                        <c:if test="${!profile.hasCustomImage}">

                            <c:if test="${profile.gender == 'Male'}">
                                <h:graphicImage url="../images/profile/abstract_boy.jpg" class="profile_image" />
                            </c:if>
                            <c:if test="${profile.gender == 'Female'}">
                                <h:graphicImage url="../images/profile/abstract_girl.jpg" class="profile_image" />
                            </c:if>

                        </c:if>
                        <div  class="middle_desc">
                            <p> Username: </p>
                            <p> Full name </p>
                            <p> Age: </p>
                            <p> Gender: </p>
                            <p> Location: </p>
                        
                        </div>
                        <div class="middle_userdetail">
                            <p>
                                <h:outputLabel value="#{profile.username}" />
                            </p>
                            <p>
                                <h:outputLabel value="#{profile.fname} #{profile.lname}" />
                            </p>
                            <p>
                                <h:outputLabel value="#{profile.age}" />
                            </p>
                            <p>
                                <h:outputLabel value="#{profile.gender}" />
                            </p>
                            <p>
                                <h:outputLabel value="#{profile.location}" />
                            </p>
                           
                        </div>
                        <div class="friendslist">
                            <div class="friends_header">
                                Friends
                            </div>
                            <c:forEach items="#{profile.friends}" var="userFriend">
                                <h:form>
                                    <h:commandLink  actionListener="#{profile.setUser(userFriend.id)}"  action="profile.xhtml?faces-redirect=true" >
                                        <div class="friend_item">
                                            <c:if test="${userFriend.hasCustomImage}">
                                                <h:graphicImage value="image?id=#{userFriend.profileImageId}" class="friends_image" />
                                            </c:if>
                                            <c:if test="${!userFriend.hasCustomImage}">
                                                <c:if test="${userFriend.gender == 'Male'}">
                                                    <h:graphicImage url="../images/profile/abstract_boy.jpg" class="friends_image" />
                                                </c:if>
                                                <c:if test="${userFriend.gender == 'Female'}">
                                                    <h:graphicImage url="../images/profile/abstract_girl.jpg" class="friends_image" />
                                                </c:if>
                                            </c:if>
                                            <div class="friend_info">
                                                #{userFriend.fname} #{userFriend.lname}
                                            </div>
                                            <div class="friend_location">
                                                #{userFriend.loc}
                                            </div>
                                        </div>
                                    </h:commandLink>
                                </h:form>
                            </c:forEach>

                        </div>
                    </div>
                    
                    <div class="bottomSection">

                        
                        <h2>
                            <br />
                            #{profile.username}'s events
                        </h2>
                       
                        <c:forEach items="#{profile.events}" var="profileEvent">      
                            <h:form>
                                <h:commandLink  actionListener="#{showEvent.setEvent(profileEvent.id)}"  action="event.xhtml?faces-redirect=true" >
                                    <div class="userEvent">

                                        <div class="eventDetails">
                                            <div class="eventHeader">
                                                #{profileEvent.title}
                                            </div>
                                            <div class="eventDesc" >
                                                #{profileEvent.description}
                                            </div>
                                            <div class="eventImage">
                                                <h:graphicImage url="../images/profile/sample_Event_image.png" class="friends_image" />
                                            </div>
                                            <div class="eventStatistics" >
                                                <br/>
                                                #{profileEvent.numberOfParticipants} people has joined this event. Created: #{profileEvent.timeCreated}
                                            </div>
                                        </div>
                                    </div>
                                </h:commandLink>
                            </h:form>
                        </c:forEach>
                    </div>                    
                </div>                
            </ui:define>
        </ui:composition>

    </body>
</html>